#!/usr/bin/env python3
"""scripts/extend_checkpoint_observation_dims.py

Weight-surgery utility: extends an rsl_rl `ActorCritic` checkpoint's first
input-layer weight matrix from N_old -> N_new observation columns, by
copying the existing N_old columns of the actor's and critic's first Linear
layer UNCHANGED and appending (N_new - N_old) freshly-initialized columns
(same default `nn.Linear` init a real layer of the new input width would
get), leaving every other parameter - both layers' biases, every deeper
layer, `std` (the action-noise parameter) - byte-identical to the source
checkpoint.

Written for BACKLOG.md's "Clutter experiment Stage SO gate: confounded, fix
is a partial-weight warm start" (2026-07-19) and
docs/superpowers/plans/2026-07-19-target-selection-clutter-implementation.md
Task 4's redo. Context: Stage SO's observation schema
(`TargetSelectionObservationsCfg`, tasks/franka/lift_env_cfg.py:255-259)
extends the base 41-dim schema (`ObservationsCfg.PolicyCfg`,
tasks/franka/lift_env_cfg.py:200-222) by exactly 2 new dims -
`distractor_distance_summary` (tasks/franka/distractor_observations.py) -
APPENDED LAST in observation-term concatenation order (confirmed live:
`TargetSelectionObservationsCfg.PolicyCfg` subclasses
`ObservationsCfg.PolicyCfg` and adds this one field after every inherited
term; `@configclass` inheritance places the subclass's own new field after
all inherited ones). At Stage SO specifically (active_distractor_count=0)
this term is a hard-zeroed constant, so a network whose first-layer weight
matrix gets 2 new columns appended (not inserted in the middle) at
positions [41,42] produces IDENTICAL output to the original 41-dim network,
since those columns are always multiplied by exactly 0.0. That is what makes
this a safe, numerically-checkable warm start rather than a lossy one - see
`--verify` below for the actual proof this script's own output holds that
property, run BEFORE any real training budget is spent on it.

Architecture assumptions (confirmed by direct inspection, 2026-07-19, of a
real `model_2998.pt` and `tasks/franka/agents/rsl_rl_ppo_cfg.py`):
  - rsl_rl (rsl-rl-lib) `ActorCritic`/`MLP`: `self.actor`/`self.critic` are
    `nn.Sequential`-like modules registering layers as `f"{idx}"`, so for
    `actor_hidden_dims=critic_hidden_dims=[256,128,64]` the real state-dict
    keys are `actor.0/.2/.4/.6.{weight,bias}` (Linear at even indices, ELU
    at odd, no params) and the same for `critic.*`. This script does NOT
    hardcode "0" - it finds the first Linear layer by taking the
    `actor.<N>.weight` / `critic.<N>.weight` key with the SMALLEST integer
    N, so it stays correct if hidden-layer count/activation ever changes.
  - `actor_obs_normalization=critic_obs_normalization=False`
    (tasks/franka/agents/rsl_rl_ppo_cfg.py:35-36) means the live
    `actor_obs_normalizer`/`critic_obs_normalizer` modules are parameter-free
    `torch.nn.Identity()` - confirmed no `*normalizer*`/running-stat keys
    exist in a real checkpoint's `model_state_dict`. No separate
    normalization-layer handling is needed or attempted here; if this script
    is ever reused against a checkpoint trained WITH obs normalization
    enabled, it will silently miss that state and produce wrong behavior -
    do not reuse blind.
  - `nn.Linear`'s own default `reset_parameters()` (PyTorch, not any rsl_rl
    custom init - confirmed live that rsl_rl's `MLP.init_weights()` exists
    but is never called anywhere in `runners/`, `algorithms/`, or
    `modules/`) is `kaiming_uniform_(weight, a=sqrt(5))`, which is
    `fan_in`-dependent (`fan_in = in_features`). The new columns are
    generated by constructing a throwaway `nn.Linear(new_dim, out_features)`
    (so its default init uses the CORRECT new fan_in, not the old one) and
    keeping only its columns beyond `old_dim` - i.e. this script asks
    "what would a real freshly-initialized layer of the new width look
    like in its new columns," not an approximation of it.
  - `--policy_only_checkpoint` (scripts/train_franka.py) only toggles
    whether `OnPolicyRunner.load()` restores `optimizer_state_dict` - it
    does NOT relax rsl_rl's `ActorCritic.load_state_dict`'s `strict=True`.
    A checkpoint whose `actor.0.weight`/`critic.0.weight` don't already
    have exactly the live env's observation width will hard-fail with a
    shape-mismatch RuntimeError regardless of this flag - confirmed by
    reading rsl_rl's own `OnPolicyRunner.load`/`ActorCritic.load_state_dict`
    directly (no cross-dimensionality resume mechanism exists anywhere in
    the installed rsl_rl or in this repo). This script exists BECAUSE that
    mechanism doesn't exist - its output checkpoint's first-layer weights
    already have the new (N_new) width baked in, so a completely ordinary
    strict `load_state_dict` against a freshly-constructed N_new-dim
    network succeeds.

Output checkpoint format mirrors
`tasks/franka/distillation.py:save_student_checkpoint`'s own
`{"model_state_dict", "optimizer_state_dict", "iter", "infos"}` shape (the
existing "policy-only checkpoint" convention `--policy_only_checkpoint`
was originally built for) - `optimizer_state_dict` is intentionally written
empty (the source checkpoint's real PPO Adam moments are for a
now-shape-incompatible 41-dim first layer; `--policy_only_checkpoint`
already exists precisely to let a fresh PPO optimizer be built instead of
resuming this stale one). `iter` defaults to PRESERVING the source
checkpoint's own `iter` value (this policy genuinely already has that many
PPO iterations of real training behind it - unlike a distillation
checkpoint's BC-loop iteration count, which counts a different process
entirely) - override with `--iter` if a different convention is wanted for
a specific dispatch. Whoever launches `train_franka.py --checkpoint
<this output> --policy_only_checkpoint --max_iterations N` must set N as
the ABSOLUTE target iteration count (train_franka.py's own convention),
i.e. `N = <preserved iter> + <desired additional iterations>`.

No Isaac Sim / GPU / rsl_rl install required - pure `torch` state-dict
surgery plus a hand-built plain `nn.Sequential` (matching rsl_rl's own
Linear/ELU layout) for `--verify`'s forward-pass check, so this runs under
any plain Python + torch (CPU is fine) - this repo's Pi host qualifies once
`torch` is pip-installed in some venv (confirmed 2026-07-19: no GPU/Isaac
Sim touched by this script at all), as does the desktop's isaac-venv or a
cloud instance's isaac-venv.

Usage:
    python3 scripts/extend_checkpoint_observation_dims.py \\
        --input model_2998.pt \\
        --output model_2998_43dim.pt \\
        --old-obs-dim 41 --new-obs-dim 43 --seed 42 --verify

`--input`/`--output` are local paths only (no gs:// fetch built in here -
download separately, e.g. `gcloud storage cp` / `gsutil cp`, to keep this
script's own dependency surface minimal and testable without network
access).
"""

from __future__ import annotations

import argparse
import copy
import re

import torch
import torch.nn as nn

# Default architecture, matching tasks/franka/agents/rsl_rl_ppo_cfg.py's
# FrankaLiftPPORunnerCfg.policy exactly (actor_hidden_dims=critic_hidden_dims,
# elu activation) - only used by --verify's hand-built forward-pass network,
# never assumed by the surgery itself (which reads real shapes straight out
# of the checkpoint's own state dict).
DEFAULT_HIDDEN_DIMS = [256, 128, 64]
DEFAULT_ACTIVATION = "elu"

_LAYER_KEY_RE = re.compile(r"^(actor|critic)\.(\d+)\.weight$")


def _find_first_layer_keys(state_dict: dict) -> dict[str, tuple[str, str]]:
    """Returns {"actor": (weight_key, bias_key), "critic": (weight_key, bias_key)}
    for the first (smallest-index) Linear layer of each of "actor"/"critic",
    found by pattern rather than assumed - see module docstring."""
    by_branch: dict[str, list[tuple[int, str]]] = {"actor": [], "critic": []}
    for key in state_dict:
        m = _LAYER_KEY_RE.match(key)
        if m:
            branch, idx = m.group(1), int(m.group(2))
            by_branch[branch].append((idx, key))
    result = {}
    for branch, entries in by_branch.items():
        if not entries:
            raise ValueError(
                f"no '{branch}.<N>.weight' keys found in model_state_dict - architecture assumption "
                f"(rsl_rl ActorCritic/MLP, see module docstring) does not hold for this checkpoint"
            )
        entries.sort(key=lambda e: e[0])
        first_idx, weight_key = entries[0]
        bias_key = f"{branch}.{first_idx}.bias"
        if bias_key not in state_dict:
            raise ValueError(f"found {weight_key} but no matching {bias_key} in model_state_dict")
        result[branch] = (weight_key, bias_key)
    return result


def extend_first_layer_weight(
    weight: torch.Tensor, old_dim: int, new_dim: int, generator: torch.Generator
) -> torch.Tensor:
    """Returns a (out_features, new_dim) tensor: `weight`'s existing
    `old_dim` columns unchanged, plus `new_dim - old_dim` new columns
    freshly initialized the way a real `nn.Linear(new_dim, out_features)`
    would initialize ALL its columns by default (kaiming_uniform_, fan_in
    = new_dim) - only the new columns are kept from that throwaway layer,
    so the new columns' distribution matches what a real from-scratch
    layer of the new width would produce, not an approximation."""
    out_features = weight.shape[0]
    if weight.shape[1] != old_dim:
        raise ValueError(f"weight has {weight.shape[1]} input columns, expected old_dim={old_dim}")
    if new_dim <= old_dim:
        raise ValueError(f"new_dim ({new_dim}) must be > old_dim ({old_dim})")
    throwaway = nn.Linear(new_dim, out_features)
    with torch.no_grad():
        nn.init.kaiming_uniform_(throwaway.weight, a=5**0.5, generator=generator)
    new_columns = throwaway.weight[:, old_dim:new_dim].detach().clone()
    extended = torch.cat([weight.detach().clone(), new_columns], dim=1)
    assert extended.shape == (out_features, new_dim)
    return extended


def extend_checkpoint(
    state: dict, old_dim: int, new_dim: int, seed: int, iter_override: int | None
) -> dict:
    """Returns a NEW top-level checkpoint dict (does not mutate `state`) in
    save_student_checkpoint's own {"model_state_dict", "optimizer_state_dict",
    "iter", "infos"} format - see module docstring for the "iter"/
    "optimizer_state_dict" conventions."""
    sd = state["model_state_dict"]
    layer_keys = _find_first_layer_keys(sd)
    new_sd = copy.deepcopy(sd)
    generator = torch.Generator().manual_seed(seed)
    for branch, (weight_key, _bias_key) in layer_keys.items():
        new_sd[weight_key] = extend_first_layer_weight(sd[weight_key], old_dim, new_dim, generator)
        # bias is per-output-neuron, unaffected by growing the input dim - left untouched by
        # the deepcopy above already.
    return {
        "model_state_dict": new_sd,
        "optimizer_state_dict": {},
        "iter": state.get("iter", 0) if iter_override is None else iter_override,
        "infos": {
            **(state.get("infos") or {}),
            "source": "extend_checkpoint_observation_dims.py",
            "surgery_old_obs_dim": old_dim,
            "surgery_new_obs_dim": new_dim,
            "surgery_seed": seed,
        },
    }


def _build_plain_mlp(in_dim: int, out_dim: int, hidden_dims: list[int], activation: str) -> nn.Sequential:
    """Hand-built nn.Sequential matching rsl_rl's own MLP layer layout
    (Linear/activation alternating, so state-dict keys "0","2","4",...
    line up with rsl_rl's real "actor.0"/"actor.2"/... naming once
    prefixed) - used ONLY by --verify, so --verify has no rsl_rl
    dependency either."""
    if activation != "elu":
        raise NotImplementedError(f"--verify's hand-built MLP only supports elu (got {activation!r})")
    layers: list[nn.Module] = []
    dims = [in_dim] + list(hidden_dims)
    for i in range(len(hidden_dims)):
        layers.append(nn.Linear(dims[i], dims[i + 1]))
        layers.append(nn.ELU())
    layers.append(nn.Linear(dims[-1], out_dim))
    return nn.Sequential(*layers)


def _load_branch_into_plain_mlp(mlp: nn.Sequential, sd: dict, branch: str) -> None:
    branch_prefix = f"{branch}."
    remapped = {k[len(branch_prefix) :]: v for k, v in sd.items() if k.startswith(branch_prefix)}
    mlp.load_state_dict(remapped, strict=True)


def verify_stage_so_equivalence(
    original_state: dict,
    extended_state: dict,
    old_dim: int,
    new_dim: int,
    hidden_dims: list[int],
    activation: str,
    batch_size: int = 64,
    atol: float = 1e-5,
    rtol: float = 1e-5,
) -> None:
    """The real numerical check this script exists to make possible: build
    the ORIGINAL `old_dim`-input network and the EXTENDED `new_dim`-input
    network as plain torch MLPs from their respective state dicts, feed the
    extended network a batch of random `new_dim`-wide observations whose
    LAST `new_dim - old_dim` columns are exactly 0.0 (the real Stage-SO
    condition - `distractor_distance_summary` is a hard-zeroed constant
    there), feed the original network the SAME batch's first `old_dim`
    columns, and assert the two networks' outputs match within `atol`/
    `rtol`. Raises AssertionError with the actual max-abs-diff on failure -
    the CLI's --verify flag surfaces this directly rather than swallowing
    it, per this task's own "if this verification fails, investigate and
    report precisely" instruction. Checks BOTH actor and critic branches.
    """
    orig_sd = original_state["model_state_dict"]
    ext_sd = extended_state["model_state_dict"]
    # Derive actor output dim (num_actions) and critic output dim (1) directly from the checkpoint's
    # own LAST Linear layer, the same self-describing approach
    # tasks/franka/distillation.py:inspect_checkpoint_shapes already uses, rather than assuming.
    def _last_layer_out_dim(sd: dict, branch: str) -> int:
        keys = [k for k in sd if re.match(rf"^{branch}\.\d+\.weight$", k)]
        keys.sort(key=lambda k: int(k.split(".")[1]))
        return int(sd[keys[-1]].shape[0])

    actor_out = _last_layer_out_dim(orig_sd, "actor")
    critic_out = _last_layer_out_dim(orig_sd, "critic")

    torch.manual_seed(0)
    obs_new = torch.randn(batch_size, new_dim)
    obs_new[:, old_dim:new_dim] = 0.0  # the real Stage-SO condition
    obs_old = obs_new[:, :old_dim].clone()

    max_diffs = {}
    for branch, out_dim in (("actor", actor_out), ("critic", critic_out)):
        old_mlp = _build_plain_mlp(old_dim, out_dim, hidden_dims, activation)
        new_mlp = _build_plain_mlp(new_dim, out_dim, hidden_dims, activation)
        _load_branch_into_plain_mlp(old_mlp, orig_sd, branch)
        _load_branch_into_plain_mlp(new_mlp, ext_sd, branch)
        old_mlp.eval()
        new_mlp.eval()
        with torch.no_grad():
            out_old = old_mlp(obs_old)
            out_new = new_mlp(obs_new)
        max_diff = (out_old - out_new).abs().max().item()
        max_diffs[branch] = max_diff
        if not torch.allclose(out_old, out_new, atol=atol, rtol=rtol):
            raise AssertionError(
                f"--verify FAILED for branch={branch!r}: outputs differ (max abs diff={max_diff:.3e}, "
                f"atol={atol}, rtol={rtol}). The 'always-zero new columns are inert' assumption may not "
                f"hold - investigate before proceeding to any real training."
            )
    print(f"--verify PASSED: actor max abs diff={max_diffs['actor']:.3e}, critic max abs diff={max_diffs['critic']:.3e}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input", required=True, help="Local path to the source rsl_rl checkpoint (.pt).")
    parser.add_argument("--output", required=True, help="Local path to write the extended checkpoint (.pt).")
    parser.add_argument("--old-obs-dim", type=int, default=41, help="Source checkpoint's observation width.")
    parser.add_argument("--new-obs-dim", type=int, default=43, help="Target observation width.")
    parser.add_argument("--seed", type=int, default=42, help="Seed for the new columns' random init.")
    parser.add_argument(
        "--iter",
        type=int,
        default=None,
        help="Override the output checkpoint's 'iter' field (default: preserve the source's own value - see "
        "module docstring's 'iter' convention).",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        default=False,
        help="After the surgery, run verify_stage_so_equivalence() and print/assert the result before "
        "writing --output. On failure, raises (nonzero exit) instead of writing an unverified checkpoint.",
    )
    parser.add_argument(
        "--hidden-dims",
        type=int,
        nargs="+",
        default=DEFAULT_HIDDEN_DIMS,
        help="Actor/critic hidden dims for --verify's hand-built MLP (default matches "
        "tasks/franka/agents/rsl_rl_ppo_cfg.py).",
    )
    parser.add_argument("--activation", type=str, default=DEFAULT_ACTIVATION, help="Activation for --verify's MLP.")
    args = parser.parse_args()

    print(f"loading {args.input} ...")
    original_state = torch.load(args.input, map_location="cpu", weights_only=False)
    orig_sd = original_state["model_state_dict"]
    layer_keys = _find_first_layer_keys(orig_sd)
    for branch, (weight_key, bias_key) in layer_keys.items():
        print(f"  found {branch} first layer: {weight_key} {tuple(orig_sd[weight_key].shape)}, "
              f"{bias_key} {tuple(orig_sd[bias_key].shape)}")
        if orig_sd[weight_key].shape[1] != args.old_obs_dim:
            raise ValueError(
                f"{weight_key} has {orig_sd[weight_key].shape[1]} input columns, but --old-obs-dim="
                f"{args.old_obs_dim} - mismatch, aborting rather than guessing."
            )
    print(f"source checkpoint 'iter'={original_state.get('iter')}")

    extended_state = extend_checkpoint(original_state, args.old_obs_dim, args.new_obs_dim, args.seed, args.iter)
    ext_sd = extended_state["model_state_dict"]
    for branch, (weight_key, _bias_key) in layer_keys.items():
        print(f"  extended {branch} first layer: {weight_key} {tuple(orig_sd[weight_key].shape)} -> "
              f"{tuple(ext_sd[weight_key].shape)}")
    print(f"output checkpoint 'iter'={extended_state['iter']} (optimizer_state_dict written empty)")

    if args.verify:
        print("running --verify (Stage-SO-condition forward-pass equivalence check) ...")
        verify_stage_so_equivalence(
            original_state, extended_state, args.old_obs_dim, args.new_obs_dim, args.hidden_dims, args.activation
        )

    torch.save(extended_state, args.output)
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
